// <auto-generated />
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dal.Migrations
{
    [DbContext(typeof(DalContext))]
    partial class DalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Dal.Entities.CartEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = "c1",
                            Name = "First Cart",
                            UserId = "a7b420a1-66cc-42b3-8bc0-5bc3abf39850"
                        },
                        new
                        {
                            Id = "c2",
                            Name = "Second Cart",
                            UserId = "a7b420a1-66cc-42b3-8bc0-5bc3abf39850"
                        });
                });

            modelBuilder.Entity("Dal.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "p1",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "859577669",
                            Name = "Vr Glasses"
                        },
                        new
                        {
                            Id = "p2",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "123431087",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = "p3",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "010624117",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = "p4",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "126908458",
                            Name = "Ventilator"
                        },
                        new
                        {
                            Id = "p5",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "839435384",
                            Name = "Charger"
                        },
                        new
                        {
                            Id = "p6",
                            Description = "This is a Descriptions. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
                            EAN = "262768465",
                            Name = "Cup"
                        });
                });

            modelBuilder.Entity("Dal.Entities.ProductToCartEntity", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartId", "ProductId");

                    b.ToTable("ProductToCartEntities");

                    b.HasData(
                        new
                        {
                            CartId = "c1",
                            ProductId = "p1",
                            Amount = 2
                        },
                        new
                        {
                            CartId = "c1",
                            ProductId = "p2",
                            Amount = 2
                        },
                        new
                        {
                            CartId = "c1",
                            ProductId = "p3",
                            Amount = 4
                        },
                        new
                        {
                            CartId = "c1",
                            ProductId = "p4",
                            Amount = 2
                        },
                        new
                        {
                            CartId = "c1",
                            ProductId = "p5",
                            Amount = 4
                        },
                        new
                        {
                            CartId = "c1",
                            ProductId = "p6",
                            Amount = 5
                        },
                        new
                        {
                            CartId = "c2",
                            ProductId = "p1",
                            Amount = 6
                        },
                        new
                        {
                            CartId = "c2",
                            ProductId = "p2",
                            Amount = 1
                        },
                        new
                        {
                            CartId = "c2",
                            ProductId = "p3",
                            Amount = 4
                        },
                        new
                        {
                            CartId = "c2",
                            ProductId = "p4",
                            Amount = 3
                        });
                });

            modelBuilder.Entity("Dal.Entities.ProductToCartEntity", b =>
                {
                    b.HasOne("Dal.Entities.CartEntity", "CartEntity")
                        .WithMany("Products")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
