//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string _2FA {
            get {
                return ResourceManager.GetString("2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_RESET_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_RESET_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_SETUP_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_SETUP_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string _2FA_AUTHENTICATION_TITLE {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} recovery codes left..
        /// </summary>
        public static string _2FA_N_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should generate a new set of recovery codes..
        /// </summary>
        public static string _2FA_N_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must generate a new set of recovery codes before you can log in with a recovery code..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate a new set of recovery codes..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string _2FA_STATUS_BROWSER_FORGET {
            get {
                return ResourceManager.GetString("2FA_STATUS_BROWSER_FORGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string ACCESS_DENIED_TEXT {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your applications and resources, even when you are offline.
        /// </summary>
        public static string Access_to_your_applications_and_resources__even_when_you_are_offline {
            get {
                return ResourceManager.GetString("Access to your applications and resources, even when you are offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the login button.
        /// </summary>
        public static string ACCOUNT_CLICK_LOGIN_LINK {
            get {
                return ResourceManager.GetString("ACCOUNT_CLICK_LOGIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log  in.
        /// </summary>
        public static string ACCOUNT_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in with a recovery code.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this machine.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_REMEMBER_MC {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_REMEMBER_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code.
        /// </summary>
        public static string ACCOUNT_LOGIN_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Azure AD.
        /// </summary>
        public static string ACCOUNT_LOGIN_WITH_AZURE_AD {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_WITH_AZURE_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See this article https://go.microsoft.com/fwlink/?LinkID=532715 for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ACCOUNT_NO_EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code required.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code verification.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string CHANGE_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator for.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable QR code generation please read our.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN1 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN2 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_STEPS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string CONFIRM_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string CONFIRM_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string CONFIRM_PASSWORD_NOT_MATCHING {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_NOT_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Access.
        /// </summary>
        public static string CONSENT_APPLICATION_ACCESS {
            get {
                return ResourceManager.GetString("CONSENT_APPLICATION_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that the authorization request quotes the code:.
        /// </summary>
        public static string CONSENT_CONFIRM_AUTH_REQUEST_QUOTES {
            get {
                return ResourceManager.GetString("CONSENT_CONFIRM_AUTH_REQUEST_QUOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the permissions you do not wish to grant..
        /// </summary>
        public static string CONSENT_IS_CHECK_UNREQUIRED {
            get {
                return ResourceManager.GetString("CONSENT_IS_CHECK_UNREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is requesting your permission.
        /// </summary>
        public static string CONSENT_IS_REQUESTING_YOUR_PERMISSION {
            get {
                return ResourceManager.GetString("CONSENT_IS_REQUESTING_YOUR_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Do Not Allow.
        /// </summary>
        public static string CONSENT_NO_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("CONSENT_NO_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string CONSENT_PERSONAL_INFORMATION {
            get {
                return ResourceManager.GetString("CONSENT_PERSONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember My Decision.
        /// </summary>
        public static string CONSENT_REMEMBER_MY_DECISION {
            get {
                return ResourceManager.GetString("CONSENT_REMEMBER_MY_DECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        public static string CONSENT_REQUIRED {
            get {
                return ResourceManager.GetString("CONSENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Allow.
        /// </summary>
        public static string CONSENT_YES_ALLOWED {
            get {
                return ResourceManager.GetString("CONSENT_YES_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CREATE_A_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_A_NEW_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password required.
        /// </summary>
        public static string CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Personal Data.
        /// </summary>
        public static string DELETE_PERSONAL_DATA {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string DELETE_PERSONAL_DATA_AND_CLOSE {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_AND_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string DELETE_PERSONAL_DATA_TEXT {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code displayed on your device.
        /// </summary>
        public static string DEVICE_ENTER_CODE_DISPLAYED_ON_DEVICE {
            get {
                return ResourceManager.GetString("DEVICE_ENTER_CODE_DISPLAYED_ON_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DEVICE_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully authorized the device.
        /// </summary>
        public static string DEVICE_SUCCESS_AUTHORIZE {
            get {
                return ResourceManager.GetString("DEVICE_SUCCESS_AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string DEVICE_USER_CODE {
            get {
                return ResourceManager.GetString("DEVICE_USER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string DISABLE_2FA {
            get {
                return ResourceManager.GetString("DISABLE_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string DISABLE_2FA_BUTTON {
            get {
                return ResourceManager.GetString("DISABLE_2FA_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fa has been disabled. You can reenable 2fa when you setup an authenticator app.
        /// </summary>
        public static string DISABLE_2FA_STATUS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS_LINK {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string DISABLE_2FA_TEXT_HEADER {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        public static string DOWNLOAD_YOUR_DATA {
            get {
                return ResourceManager.GetString("DOWNLOAD_YOUR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Email.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MFA.
        /// </summary>
        public static string ERROR_ENABLE_MFA {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client application requires you to have MFA enabled. Enable this and try to sign in again..
        /// </summary>
        public static string ERROR_ENABLE_MFA_CLIENT_APP_REQUIRES_MFA {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_CLIENT_APP_REQUIRES_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable MFA Error.
        /// </summary>
        public static string ERROR_ENABLE_MFA_ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enable MFA to login here:.
        /// </summary>
        public static string ERROR_ENABLE_MFA_YOU_CAN_ENABLE_HERE {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_YOU_CAN_ENABLE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account.
        /// </summary>
        public static string EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with {0}. Please enter an email address for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string EXTERNAL_LOGIN_TEXT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another service to log in..
        /// </summary>
        public static string EXTERNAL_LOGINS_ADD_ANOTHER_SERVICE_TO_LOGIN {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_ADD_ANOTHER_SERVICE_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string EXTERNAL_LOGINS_REGISTERED_LOGIN {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_REGISTERED_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string EXTERNAL_LOGINS_TITLE {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from external provider: {0}.
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading external login information during confirmation..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_CONFIRMATION {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading external login information..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_INFO {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a FIDO2 Key.
        /// </summary>
        public static string FIDO2_ADD_A_KEY {
            get {
                return ResourceManager.GetString("FIDO2_ADD_A_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify assertion.
        /// </summary>
        public static string FIDO2_COULD_NOT_VERIFY_ASSERTION {
            get {
                return ResourceManager.GetString("FIDO2_COULD_NOT_VERIFY_ASSERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with FIDO2 MFA.
        /// </summary>
        public static string FIDO2_LOGIN_WITH_MFA {
            get {
                return ResourceManager.GetString("FIDO2_LOGIN_WITH_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIDO2 Multi-factor authentication.
        /// </summary>
        public static string FIDO2_MULTI_FACTOR_AUTHENTICATION {
            get {
                return ResourceManager.GetString("FIDO2_MULTI_FACTOR_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create credentials in browser. Probably because the username is already registered with your authenticator. Please change username or authenticator..
        /// </summary>
        public static string FIDO2_REGISTRATION_ERROR {
            get {
                return ResourceManager.GetString("FIDO2_REGISTRATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported browsers.
        /// </summary>
        public static string FIDO2_SUPPORTED_BROWSERS {
            get {
                return ResourceManager.GetString("FIDO2_SUPPORTED_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap your security key to finish registration..
        /// </summary>
        public static string FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION {
            get {
                return ResourceManager.GetString("FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap your security key to login. .
        /// </summary>
        public static string FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN {
            get {
                return ResourceManager.GetString("FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load two-factor authenticated user..
        /// </summary>
        public static string FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER {
            get {
                return ResourceManager.GetString("FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown credentials.
        /// </summary>
        public static string FIDO2_UNKNOWN_CREDENTIALS {
            get {
                return ResourceManager.GetString("FIDO2_UNKNOWN_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string FIDO2_USER_NOTFOUND {
            get {
                return ResourceManager.GetString("FIDO2_USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string FIDO2_USERNAME {
            get {
                return ResourceManager.GetString("FIDO2_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username was not registered.
        /// </summary>
        public static string FIDO2_USERNAME_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("FIDO2_USERNAME_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: Your browser does not seem to support WebAuthn yet..
        /// </summary>
        public static string FIDO2_WEBAUTHN_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("FIDO2_WEBAUTHN_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string FORGET_THIS_BROWSER {
            get {
                return ResourceManager.GetString("FORGET_THIS_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION_TEXT {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GENERATE {
            get {
                return ResourceManager.GetString("GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_INFO_LOSE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_INFO_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT_LINK {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string GENERATE_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants.
        /// </summary>
        public static string GRANTS {
            get {
                return ResourceManager.GetString("GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Grants.
        /// </summary>
        public static string GRANTS_API_GRANTS {
            get {
                return ResourceManager.GetString("GRANTS_API_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Application Access.
        /// </summary>
        public static string GRANTS_CLIENT_APP_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_CLIENT_APP_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string GRANTS_CREATED {
            get {
                return ResourceManager.GetString("GRANTS_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string GRANTS_EXPIRES {
            get {
                return ResourceManager.GetString("GRANTS_EXPIRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Grants.
        /// </summary>
        public static string GRANTS_IDENTITY_GRANTS {
            get {
                return ResourceManager.GetString("GRANTS_IDENTITY_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the list of applications you have given access to and the names of the resources they have access to..
        /// </summary>
        public static string GRANTS_INFO {
            get {
                return ResourceManager.GetString("GRANTS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not given access to any applications.
        /// </summary>
        public static string GRANTS_NO_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Access.
        /// </summary>
        public static string GRANTS_REVOKE_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_REVOKE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authenticator code..
        /// </summary>
        public static string INVALID_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("INVALID_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string INVALID_CODE {
            get {
                return ResourceManager.GetString("INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick at least one permission..
        /// </summary>
        public static string INVALID_CONSENT_PERMISSION {
            get {
                return ResourceManager.GetString("INVALID_CONSENT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        public static string INVALID_CONSENT_SELECTION {
            get {
                return ResourceManager.GetString("INVALID_CONSENT_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string INVALID_LOGIN_ATTEMPT {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recovery code entered..
        /// </summary>
        public static string INVALID_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("INVALID_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        public static string Invalid_selection {
            get {
                return ResourceManager.GetString("Invalid selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid..
        /// </summary>
        public static string INVALID_VERFICATION_CODE {
            get {
                return ResourceManager.GetString("INVALID_VERFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} must derive from {1}&lt;{2}&gt;..
        /// </summary>
        public static string InvalidManagerType {
            get {
                return ResourceManager.GetString("InvalidManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided PasswordHasherCompatibilityMode is invalid..
        /// </summary>
        public static string InvalidPasswordHasherCompatibilityMode {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The iteration count must be a positive integer..
        /// </summary>
        public static string InvalidPasswordHasherIterationCount {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LOCKED_OUT {
            get {
                return ResourceManager.GetString("LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LOCKED_OUT_TEXT {
            get {
                return ResourceManager.GetString("LOCKED_OUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to.
        /// </summary>
        public static string LOGOUT_RETURN_TO {
            get {
                return ResourceManager.GetString("LOGOUT_RETURN_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of the application..
        /// </summary>
        public static string LOGOUT_TEXT {
            get {
                return ResourceManager.GetString("LOGOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string MANAGE_CHANGE_ACCOUNT_SETTINGS {
            get {
                return ResourceManager.GetString("MANAGE_CHANGE_ACCOUNT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string MANAGE_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("MANAGE_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIdentity must be called on the service collection..
        /// </summary>
        public static string MustCallAddIdentity {
            get {
                return ResourceManager.GetString("MustCallAddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password required.
        /// </summary>
        public static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IPersonalDataProtector service was registered, this is required when ProtectPersonalData = true..
        /// </summary>
        public static string NoPersonalDataProtector {
            get {
                return ResourceManager.GetString("NoPersonalDataProtector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RoleType was specified, try AddRoles&lt;TRole&gt;()..
        /// </summary>
        public static string NoRoleType {
            get {
                return ResourceManager.GetString("NoRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IUserTwoFactorTokenProvider&lt;{0}&gt; named &apos;{1}&apos; is registered..
        /// </summary>
        public static string NoTokenProvider {
            get {
                return ResourceManager.GetString("NoTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User security stamp cannot be null..
        /// </summary>
        public static string NullSecurityStamp {
            get {
                return ResourceManager.GetString("NullSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Access.
        /// </summary>
        public static string Offline_Access {
            get {
                return ResourceManager.GetString("Offline Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must use at least {0} different characters..
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PERSONAL_DATA {
            get {
                return ResourceManager.GetString("PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string PERSONAL_DATA_DELETEINFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_DELETEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string PERSONAL_DATA_INFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string Recovery_codes {
            get {
                return ResourceManager.GetString("Recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code redemption failed..
        /// </summary>
        public static string RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string REGISTER_AS_NEW_USER {
            get {
                return ResourceManager.GetString("REGISTER_AS_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Browser.
        /// </summary>
        public static string REMEMBER_BROWSER {
            get {
                return ResourceManager.GetString("REMEMBER_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string REMEMBER_ME {
            get {
                return ResourceManager.GetString("REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string RESET_AUTHENTICATOR_INFO {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string RESET_AUTHENTICATOR_KEY {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app key has been reset, you will need to configure your authenticator app using the new key..
        /// </summary>
        public static string RESET_AUTHENTICATOR_STATUS {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app. If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string RESET_AUTHENTICATOR_TEXT {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log in.
        /// </summary>
        public static string RESET_PASSWORD_CLICK_HERE_TO_LOGIN {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CLICK_HERE_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_CLICK_HERE {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_CLICK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_TEXT1 {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string RESET_PASSWORD_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string RESET_PASSWORD_YOUR_PASSWORD_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_YOUR_PASSWORD_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string RESET_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("RESET_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} does not exist..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Verification Code.
        /// </summary>
        public static string SEND_VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string SEND_VERIFICATION_CODE_SELECT {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_CODE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string SEND_VERIFICATION_EMAIL {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SET_PASSWORD {
            get {
                return ResourceManager.GetString("SET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string SET_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("SET_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string SET_PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("SET_PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string SET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("SET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was added..
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_ADDED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_REMOVED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated new recovery codes..
        /// </summary>
        public static string STATUS_GENERATE_CODES {
            get {
                return ResourceManager.GetString("STATUS_GENERATE_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string STATUS_MESSAGE_PROFILE_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("STATUS_MESSAGE_PROFILE_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string STATUS_PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("STATUS_PROFILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent. Please check your email..
        /// </summary>
        public static string STATUS_UPDATE_PROFILE_EMAIL_SEND {
            get {
                return ResourceManager.GetString("STATUS_UPDATE_PROFILE_EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IProtectedUserStore&lt;TUser&gt; which is required when ProtectPersonalData = true..
        /// </summary>
        public static string StoreNotIProtectedUserStore {
            get {
                return ResourceManager.GetString("StoreNotIProtectedUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableRoleStore&lt;TRole&gt;..
        /// </summary>
        public static string StoreNotIQueryableRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableUserStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIQueryableUserStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IRoleClaimStore&lt;TRole&gt;..
        /// </summary>
        public static string StoreNotIRoleClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIRoleClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserAuthenticationTokenStore&lt;User&gt;..
        /// </summary>
        public static string StoreNotIUserAuthenticationTokenStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticationTokenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserAuthenticatorKeyStore&lt;User&gt;..
        /// </summary>
        public static string StoreNotIUserAuthenticatorKeyStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticatorKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserClaimStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIUserClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserConfirmationStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserConfirmationStore {
            get {
                return ResourceManager.GetString("StoreNotIUserConfirmationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserEmailStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserEmailStore {
            get {
                return ResourceManager.GetString("StoreNotIUserEmailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserLockoutStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserLockoutStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLockoutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserLoginStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserLoginStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLoginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserPasswordStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserPasswordStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPasswordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserPhoneNumberStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserPhoneNumberStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPhoneNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserRoleStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIUserRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserSecurityStampStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotIUserSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserTwoFactorRecoveryCodeStore&lt;User&gt;..
        /// </summary>
        public static string StoreNotIUserTwoFactorRecoveryCodeStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorRecoveryCodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserTwoFactorStore&lt;TUser&gt;..
        /// </summary>
        public static string StoreNotIUserTwoFactorStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string The__0__must_be_at_least__2__and_at_max__1__characters_long_ {
            get {
                return ResourceManager.GetString("The {0} must be at least {2} and at max {1} characters long.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor code is required.
        /// </summary>
        public static string TWOFACTORCODE_REQUIRED {
            get {
                return ResourceManager.GetString("TWOFACTORCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string UNSUCCESSFUL_LOGIN_WITH_SERVICE {
            get {
                return ResourceManager.GetString("UNSUCCESSFUL_LOGIN_WITH_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UPDATE_PASSWORD {
            get {
                return ResourceManager.GetString("UPDATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string USER_NOTFOUND {
            get {
                return ResourceManager.GetString("USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string User_profile {
            get {
                return ResourceManager.GetString("User profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout is not enabled for this user..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not exist..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role &apos;{0}&apos;..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is required.
        /// </summary>
        public static string VERIFICATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VERIFY {
            get {
                return ResourceManager.GetString("VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to logout of IdentityServer?.
        /// </summary>
        public static string WOULD_YOU_LIKE_TO_LOGOUT {
            get {
                return ResourceManager.GetString("WOULD_YOU_LIKE_TO_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick at least one permission.
        /// </summary>
        public static string You_must_pick_at_least_one_permission {
            get {
                return ResourceManager.GetString("You must pick at least one permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string Your_email_address {
            get {
                return ResourceManager.GetString("Your email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user identifier.
        /// </summary>
        public static string Your_user_identifier {
            get {
                return ResourceManager.GetString("Your user identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user profile information (first name, last name, etc.).
        /// </summary>
        public static string Your_user_profile_information__first_name__last_name__etc__ {
            get {
                return ResourceManager.GetString("Your user profile information (first name, last name, etc.)", resourceCulture);
            }
        }
    }
}
