//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-Authentifizierung.
        /// </summary>
        public static string _2FA {
            get {
                return ResourceManager.GetString("2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügen Sie eine Authentifizierungs-App hinzu.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungs-App zurücksetzen.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_RESET_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_RESET_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungs-App einrichten.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_SETUP_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_SETUP_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-Authentifizierung (2FA).
        /// </summary>
        public static string _2FA_AUTHENTICATION_TITLE {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben {0} Wiederherstellungscodes übrig..
        /// </summary>
        public static string _2FA_N_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sollten eine neue Reihe von Wiederherstellungscodes generieren..
        /// </summary>
        public static string _2FA_N_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keine Wiederherstellungscodes mehr..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen einen neuen Satz von Wiederherstellungscodes generieren, bevor Sie sich mit einem Wiederherstellungscode anmelden können..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben 1 Wiederherstellungscode übrig..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können einen neuen Satz von Wiederherstellungscodes generieren..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der aktuelle Browser wurde vergessen. Wenn Sie sich erneut von diesem Browser aus anmelden, werden Sie aufgefordert, Ihren 2FA-Code einzugeben..
        /// </summary>
        public static string _2FA_STATUS_BROWSER_FORGET {
            get {
                return ResourceManager.GetString("2FA_STATUS_BROWSER_FORGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff verweigert.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen Zugriff auf diese Ressource..
        /// </summary>
        public static string ACCESS_DENIED_TEXT {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriff auf Ihre Anwendungen und Ressourcen, auch wenn Sie offline sind.
        /// </summary>
        public static string Access_to_your_applications_and_resources__even_when_you_are_offline {
            get {
                return ResourceManager.GetString("Access to your applications and resources, even when you are offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf den Login-Link.
        /// </summary>
        public static string ACCOUNT_CLICK_LOGIN_LINK {
            get {
                return ResourceManager.GetString("ACCOUNT_CLICK_LOGIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        public static string ACCOUNT_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-Authentifizierung.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie keinen Zugriff auf Ihr Authentifizierungsgerät? Sie können.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen mit einem Wiederherstellungscode.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerät merken.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_REMEMBER_MC {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_REMEMBER_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Login ist mit einer Authentifizierungs-App geschützt. Geben Sie unten Ihren Authentifizierungscode ein..
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungscode.
        /// </summary>
        public static string ACCOUNT_LOGIN_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Azure AD einloggen.
        /// </summary>
        public static string ACCOUNT_LOGIN_WITH_AZURE_AD {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_WITH_AZURE_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind keine externen Authentifizierungsdienste konfiguriert. Informationen zum Einrichten dieser ASP.NET-Anwendung für die Anmeldung über externe Dienste finden Sie in diesem Artikel unter https://go.microsoft.com/fwlink/?LinkID=532715. .
        /// </summary>
        public static string ACCOUNT_NO_EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellungscode.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellungscode erforderlich.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung des Wiederherstellungscodes.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben sich mit einem Wiederherstellungscode angemeldet. Diese Anmeldung wird nicht gespeichert, bis Sie beim Anmelden einen Authenticator-App-Code angeben oder 2FA deaktivieren und sich erneut anmelden..
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwenden Sie einen anderen Dienst, um sich anzumelden..
        /// </summary>
        public static string ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwenden Sie einen lokalen Benutzer um sich anzumelden..
        /// </summary>
        public static string ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungs-App.
        /// </summary>
        public static string AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde geändert..
        /// </summary>
        public static string CHANGE_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code ist erforderlich.
        /// </summary>
        public static string CODE_REQUIRED {
            get {
                return ResourceManager.GetString("CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistischer Parallelitätsfehler, Objekt wurde geändert..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungs-App konfigurieren.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden Sie eine Zwei-Faktor-Authentifizierungs-App wie Microsoft Authenticator für.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator für.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zur Aktivierung der QR-Code-Generierung lesen Sie bitte unsere .
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachdem Sie den QR-Code gescannt oder den oben genannten Schlüssel eingegeben haben, erhalten Sie von der Zwei-Faktor-Authentifizierungs-App einen eindeutigen Code. Geben Sie den Code in das Bestätigungsfeld ein..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentation.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen Sie den QR-Code oder geben Sie diesen Schlüssel .
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN1 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Ihre Zwei-Faktor-Authentifizierungs-App ein. Leerzeichen, Groß- und Kleinschreibung spielen keine Rolle..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN2 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führen Sie die folgenden Schritte aus, um eine Authentifizierungs-App zu verwenden:.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_STEPS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse verifizieren.
        /// </summary>
        public static string CONFIRM_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für die Verifizierung Ihrer E-Mail-Adresse..
        /// </summary>
        public static string CONFIRM_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort bestätigen.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort und Passwortbestätigung stimmen nicht überein..
        /// </summary>
        public static string CONFIRM_PASSWORD_NOT_MATCHING {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_NOT_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen Sie Ihre E-Mail-Adresse.
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätigen Sie Ihr Konto, indem Sie hier &lt;a href=&apos;{0}&apos;&gt;klicken&lt;/a&gt;. .
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikationszugriff.
        /// </summary>
        public static string CONSENT_APPLICATION_ACCESS {
            get {
                return ResourceManager.GetString("CONSENT_APPLICATION_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätigen Sie, dass die Autorisierungsanfrage den Code enthält:.
        /// </summary>
        public static string CONSENT_CONFIRM_AUTH_REQUEST_QUOTECONSENT_CONFIRM_AUTH_REQUEST_QUOTE {
            get {
                return ResourceManager.GetString("CONSENT_CONFIRM_AUTH_REQUEST_QUOTECONSENT_CONFIRM_AUTH_REQUEST_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätigen Sie, dass die Autorisierungsanfrage den Code enthät:.
        /// </summary>
        public static string CONSENT_CONFIRM_AUTH_REQUEST_QUOTES {
            get {
                return ResourceManager.GetString("CONSENT_CONFIRM_AUTH_REQUEST_QUOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie die Berechtigung ab, welche Sie nicht geben möchten..
        /// </summary>
        public static string CONSENT_IS_CHECK_UNREQUIRED {
            get {
                return ResourceManager.GetString("CONSENT_IS_CHECK_UNREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erfordert Ihre Berechtigung.
        /// </summary>
        public static string CONSENT_IS_REQUESTING_YOUR_PERMISSION {
            get {
                return ResourceManager.GetString("CONSENT_IS_REQUESTING_YOUR_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein, verweigern.
        /// </summary>
        public static string CONSENT_NO_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("CONSENT_NO_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönliche Informationen.
        /// </summary>
        public static string CONSENT_PERSONAL_INFORMATION {
            get {
                return ResourceManager.GetString("CONSENT_PERSONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen merken.
        /// </summary>
        public static string CONSENT_REMEMBER_MY_DECISION {
            get {
                return ResourceManager.GetString("CONSENT_REMEMBER_MY_DECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pflichtfeld).
        /// </summary>
        public static string CONSENT_REQUIRED {
            get {
                return ResourceManager.GetString("CONSENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, erlauben.
        /// </summary>
        public static string CONSENT_YES_ALLOWED {
            get {
                return ResourceManager.GetString("CONSENT_YES_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Konto erstellen.
        /// </summary>
        public static string CREATE_A_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_A_NEW_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelles Passwort.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelles Passwort erforderlich.
        /// </summary>
        public static string CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unbekannter Fehler ist aufgetreten..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönliche Daten löschen.
        /// </summary>
        public static string DELETE_PERSONAL_DATA {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten löschen und mein Konto schließen.
        /// </summary>
        public static string DELETE_PERSONAL_DATA_AND_CLOSE {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_AND_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch das Löschen dieser Daten wird Ihr Konto dauerhaft gelöscht. Dies kann nicht wiederhergestellt werden..
        /// </summary>
        public static string DELETE_PERSONAL_DATA_TEXT {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Code ein, der auf Ihrem Gerät angezeigt wird.
        /// </summary>
        public static string DEVICE_ENTER_CODE_DISPLAYED_ON_DEVICE {
            get {
                return ResourceManager.GetString("DEVICE_ENTER_CODE_DISPLAYED_ON_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich.
        /// </summary>
        public static string DEVICE_SUCCESS {
            get {
                return ResourceManager.GetString("DEVICE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben das Gerät erfolgreich autorisiert.
        /// </summary>
        public static string DEVICE_SUCCESS_AUTHORIZE {
            get {
                return ResourceManager.GetString("DEVICE_SUCCESS_AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Code.
        /// </summary>
        public static string DEVICE_USER_CODE {
            get {
                return ResourceManager.GetString("DEVICE_USER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-Authentifizierung (2FA) deaktivieren.
        /// </summary>
        public static string DISABLE_2FA {
            get {
                return ResourceManager.GetString("DISABLE_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA deaktivieren.
        /// </summary>
        public static string DISABLE_2FA_BUTTON {
            get {
                return ResourceManager.GetString("DISABLE_2FA_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA wurde deaktiviert. Sie können 2FA aktivieren, wenn Sie eine Authenticator-App einrichten.
        /// </summary>
        public static string DISABLE_2FA_STATUS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch das Deaktivieren von 2FA werden die in Authenticator-Apps verwendeten Schlüssel nicht geändert. Wenn Sie den in einer Authenticator-App verwendeten Schlüssel ändern möchten, sollten Sie Ihre Authentifizierungsschlüssel.
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurücksetzen..
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS_LINK {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Aktion deaktiviert nur 2FA..
        /// </summary>
        public static string DISABLE_2FA_TEXT_HEADER {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden Sie Ihre Daten herunter.
        /// </summary>
        public static string DOWNLOAD_YOUR_DATA {
            get {
                return ResourceManager.GetString("DOWNLOAD_YOUR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Rollenname &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername &apos;{0}&apos; ist bereits vergeben..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige E-Mail-Adresse.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail-Adresse erforderlich.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA aktivieren.
        /// </summary>
        public static string ERROR_ENABLE_MFA {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Client-Anwendung erfordert, dass Sie MFA aktiviert haben. Aktivieren Sie dies und versuchen Sie, sich erneut anzumelden..
        /// </summary>
        public static string ERROR_ENABLE_MFA_CLIENT_APP_REQUIRES_MFA {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_CLIENT_APP_REQUIRES_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Aktivierungsfehler.
        /// </summary>
        public static string ERROR_ENABLE_MFA_ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können MFA hier zum Einloggen aktivieren:.
        /// </summary>
        public static string ERROR_ENABLE_MFA_YOU_CAN_ENABLE_HERE {
            get {
                return ResourceManager.GetString("ERROR_ENABLE_MFA_YOU_CAN_ENABLE_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinden Sie Ihr {0} Konto.
        /// </summary>
        public static string EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben sich erfolgreich mit {0} authentifiziert. Bitte geben Sie unten eine E-Mail-Adresse für diese Seite ein und klicken Sie auf die Registrierenknopf, um die Anmeldung abzuschließen..
        /// </summary>
        public static string EXTERNAL_LOGIN_TEXT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externe Logins.
        /// </summary>
        public static string EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügen Sie einen weiteren Dienst hinzu, um sich anzumelden..
        /// </summary>
        public static string EXTERNAL_LOGINS_ADD_ANOTHER_SERVICE_TO_LOGIN {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_ADD_ANOTHER_SERVICE_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierte Anmeldungen.
        /// </summary>
        public static string EXTERNAL_LOGINS_REGISTERED_LOGIN {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_REGISTERED_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externen Logins verwalten.
        /// </summary>
        public static string EXTERNAL_LOGINS_TITLE {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler von externem Anbieter: {0}.
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der externen Anmeldeinformationen während der Bestätigung..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_CONFIRMATION {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der externen Anmeldeinformationen..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_INFO {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügen Sie einen FIDO2-Schlüssel hinzu.
        /// </summary>
        public static string FIDO2_ADD_A_KEY {
            get {
                return ResourceManager.GetString("FIDO2_ADD_A_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion konnte nicht überprüft werden.
        /// </summary>
        public static string FIDO2_COULD_NOT_VERIFY_ASSERTION {
            get {
                return ResourceManager.GetString("FIDO2_COULD_NOT_VERIFY_ASSERTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melden Sie sich mit FIDO2 MFA an.
        /// </summary>
        public static string FIDO2_LOGIN_WITH_MFA {
            get {
                return ResourceManager.GetString("FIDO2_LOGIN_WITH_MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIDO2 Multi-Faktor-Authentifizierung.
        /// </summary>
        public static string FIDO2_MULTI_FACTOR_AUTHENTICATION {
            get {
                return ResourceManager.GetString("FIDO2_MULTI_FACTOR_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldeinformationen im Browser konnten nicht erstellt werden. Wahrscheinlich, weil der Benutzername bereits bei Ihrem Authentifikator registriert ist. Bitte ändern Sie den Benutzernamen oder den Authentifikator..
        /// </summary>
        public static string FIDO2_REGISTRATION_ERROR {
            get {
                return ResourceManager.GetString("FIDO2_REGISTRATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützte Browser.
        /// </summary>
        public static string FIDO2_SUPPORTED_BROWSERS {
            get {
                return ResourceManager.GetString("FIDO2_SUPPORTED_BROWSERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tippen Sie auf Ihren Sicherheitsschlüssel, um die Registrierung abzuschließen..
        /// </summary>
        public static string FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION {
            get {
                return ResourceManager.GetString("FIDO2_TAP_YOUR_SECURITY_KEY_TO_FINISH_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tippen Sie auf Ihren Sicherheitsschlüssel, um sich anzumelden..
        /// </summary>
        public static string FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN {
            get {
                return ResourceManager.GetString("FIDO2_TAP_YOUR_SECURITY_KEY_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-authentifizierter Benutzer kann nicht geladen werden..
        /// </summary>
        public static string FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER {
            get {
                return ResourceManager.GetString("FIDO2_UNABLE_TO_LOAD_2FA_AUTHENTICATED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Anmeldeinformationen.
        /// </summary>
        public static string FIDO2_UNKNOWN_CREDENTIALS {
            get {
                return ResourceManager.GetString("FIDO2_UNKNOWN_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer mit der ID &apos;{0}&apos; kann nicht geladen werden..
        /// </summary>
        public static string FIDO2_USER_NOTFOUND {
            get {
                return ResourceManager.GetString("FIDO2_USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string FIDO2_USERNAME {
            get {
                return ResourceManager.GetString("FIDO2_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername wurde nicht registriert.
        /// </summary>
        public static string FIDO2_USERNAME_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("FIDO2_USERNAME_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beachten Sie: Ihr Browser scheint WebAuthn noch nicht zu unterstützen..
        /// </summary>
        public static string FIDO2_WEBAUTHN_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("FIDO2_WEBAUTHN_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser vergessen.
        /// </summary>
        public static string FORGET_THIS_BROWSER {
            get {
                return ResourceManager.GetString("FORGET_THIS_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort-Bestätigung vergessen.
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfen Sie Ihre E-Mail-Adresse, um Ihr Passwort zurückzusetzen..
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION_TEXT {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie Ihre E-Mail-Adresse ein..
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generieren.
        /// </summary>
        public static string GENERATE {
            get {
                return ResourceManager.GetString("GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellungscodes für 2-Faktor-Authentifizierung (2FA) generieren.
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie Ihr Gerät verlieren und keine Wiederherstellungscodes haben, verlieren Sie den Zugriff auf Ihr Konto..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_INFO_LOSE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_INFO_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legen Sie diese Codes an einem sicheren Ort ab..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch die Erstellung neuer Wiederherstellungscodes werden die in Authenticator-Apps verwendeten Schlüssel nicht geändert. Wenn Sie den in einer Authenticator-App verwendeten Schlüssel ändern möchten, sollten Sie Ihre Authentifizierungsschlüssel zurücksetzen..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurücksetzen..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT_LINK {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiere Wiederherstellungscodes.
        /// </summary>
        public static string GENERATE_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genehmigung.
        /// </summary>
        public static string GRANTS {
            get {
                return ResourceManager.GetString("GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Genehmigung.
        /// </summary>
        public static string GRANTS_API_GRANTS {
            get {
                return ResourceManager.GetString("GRANTS_API_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client-Anwendungszugriff.
        /// </summary>
        public static string GRANTS_CLIENT_APP_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_CLIENT_APP_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt.
        /// </summary>
        public static string GRANTS_CREATED {
            get {
                return ResourceManager.GetString("GRANTS_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfällt.
        /// </summary>
        public static string GRANTS_EXPIRES {
            get {
                return ResourceManager.GetString("GRANTS_EXPIRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identität Genehmigung.
        /// </summary>
        public static string GRANTS_IDENTITY_GRANTS {
            get {
                return ResourceManager.GetString("GRANTS_IDENTITY_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unten finden Sie eine Liste der Anwendungen, auf die Sie Zugriff haben, und die Namen der Ressourcen, auf die Sie Zugriff haben..
        /// </summary>
        public static string GRANTS_INFO {
            get {
                return ResourceManager.GetString("GRANTS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen Zugriff auf Anwendungen gewährt.
        /// </summary>
        public static string GRANTS_NO_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugangsberechtigung aufheben.
        /// </summary>
        public static string GRANTS_REVOKE_ACCESS {
            get {
                return ResourceManager.GetString("GRANTS_REVOKE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das eingegebene Passwort ist nicht korrekt.
        /// </summary>
        public static string INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Authentifizierungscode.
        /// </summary>
        public static string INVALID_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("INVALID_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Code..
        /// </summary>
        public static string INVALID_CODE {
            get {
                return ResourceManager.GetString("INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen mindestens eine Berechtigung auswählen..
        /// </summary>
        public static string INVALID_CONSENT_PERMISSION {
            get {
                return ResourceManager.GetString("INVALID_CONSENT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Auswahl.
        /// </summary>
        public static string INVALID_CONSENT_SELECTION {
            get {
                return ResourceManager.GetString("INVALID_CONSENT_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Anmeldeversuch..
        /// </summary>
        public static string INVALID_LOGIN_ATTEMPT {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Wiederherstellungscode eingegeben.
        /// </summary>
        public static string INVALID_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("INVALID_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Auswahl.
        /// </summary>
        public static string Invalid_selection {
            get {
                return ResourceManager.GetString("Invalid selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Bestätigungscode ist ungültig..
        /// </summary>
        public static string INVALID_VERFICATION_CODE {
            get {
                return ResourceManager.GetString("INVALID_VERFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige E-Mail Adresse &apos;{0}&apos;.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Typ {0} muss von {1} &lt;{2}&gt; abgeleitet sein..
        /// </summary>
        public static string InvalidManagerType {
            get {
                return ResourceManager.GetString("InvalidManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene PasswordHasherCompatibilityMode ist ungültig..
        /// </summary>
        public static string InvalidPasswordHasherCompatibilityMode {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Iterationszähler muss eine positive Zahl sein..
        /// </summary>
        public static string InvalidPasswordHasherIterationCount {
            get {
                return ResourceManager.GetString("InvalidPasswordHasherIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Rollenname &apos;{0}&apos; ist ungültig..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername &apos;{0}&apos; ist ungültig und darf nur Buchstaben oder Ziffern enthalten..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesperrt.
        /// </summary>
        public static string LOCKED_OUT {
            get {
                return ResourceManager.GetString("LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Konto wurde gesperrt. Bitte versuchen Sie es später erneut..
        /// </summary>
        public static string LOCKED_OUT_TEXT {
            get {
                return ResourceManager.GetString("LOCKED_OUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Benutzer mit diesem Login ist bereits vorhanden..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausloggen.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zu.
        /// </summary>
        public static string LOGOUT_RETURN_TO {
            get {
                return ResourceManager.GetString("LOGOUT_RETURN_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben sich erfolgreich von der Anwendung abgemeldet..
        /// </summary>
        public static string LOGOUT_TEXT {
            get {
                return ResourceManager.GetString("LOGOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie Ihre Benutzereinstellungen.
        /// </summary>
        public static string MANAGE_CHANGE_ACCOUNT_SETTINGS {
            get {
                return ResourceManager.GetString("MANAGE_CHANGE_ACCOUNT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzereinstellungen ändern.
        /// </summary>
        public static string MANAGE_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("MANAGE_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIdentity muss für die Service Collection aufgerufen werden..
        /// </summary>
        public static string MustCallAddIdentity {
            get {
                return ResourceManager.GetString("MustCallAddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort erforderlich.
        /// </summary>
        public static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein IPersonalDataProtector Dienst registriert. Dies ist erforderlich, wenn ProtectPersonalData = true ist..
        /// </summary>
        public static string NoPersonalDataProtector {
            get {
                return ResourceManager.GetString("NoPersonalDataProtector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Rollentyp angegeben. Versuchen Sie es mit AddRoles &lt;TRole&gt; ()..
        /// </summary>
        public static string NoRoleType {
            get {
                return ResourceManager.GetString("NoRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist kein IUserTwoFactorTokenProvider &lt;{0}&gt; mit dem Namen &apos;{1}&apos; registriert..
        /// </summary>
        public static string NoTokenProvider {
            get {
                return ResourceManager.GetString("NoTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Sicherheitsstempel des Benutzers darf nicht null sein..
        /// </summary>
        public static string NullSecurityStamp {
            get {
                return ResourceManager.GetString("NullSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline-Zugriff.
        /// </summary>
        public static string Offline_Access {
            get {
                return ResourceManager.GetString("Offline Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oder.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort erforderlich.
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsches Passwort.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens eine Ziffer haben (&apos;0&apos; - &apos;9&apos;)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens einen Kleinbuchstaben haben (&apos;a&apos; - &apos;z&apos;)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens ein nicht alphanumerisches Zeichen enthalten..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens {0} unterschiedliche Zeichen enthalten..
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens einen Großbuchstaben enthalten (&apos;A&apos; - &apos;Z&apos;)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter müssen mindestens {0} Zeichen enthalten..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persönliche Daten.
        /// </summary>
        public static string PERSONAL_DATA {
            get {
                return ResourceManager.GetString("PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch das Löschen dieser Daten wird Ihr Konto dauerhaft gelöscht. Dies kann nicht wiederhergestellt werden..
        /// </summary>
        public static string PERSONAL_DATA_DELETEINFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_DELETEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Konto enthält persönliche Daten, die Sie uns gegeben haben. Auf dieser Seite können Sie diese Daten herunterladen oder löschen..
        /// </summary>
        public static string PERSONAL_DATA_INFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellungscodes.
        /// </summary>
        public static string Recovery_codes {
            get {
                return ResourceManager.GetString("Recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Einlösen des Wiederherstellungscodes..
        /// </summary>
        public static string RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als neuer Benutzer/-in registrieren.
        /// </summary>
        public static string REGISTER_AS_NEW_USER {
            get {
                return ResourceManager.GetString("REGISTER_AS_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser merken.
        /// </summary>
        public static string REMEMBER_BROWSER {
            get {
                return ResourceManager.GetString("REMEMBER_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login merken.
        /// </summary>
        public static string REMEMBER_ME {
            get {
                return ResourceManager.GetString("REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie Ihren Authentifikatorschlüssel zurücksetzen, funktioniert Ihre Authentifizierungsanwendung erst, wenn Sie sie neu konfigurieren..
        /// </summary>
        public static string RESET_AUTHENTICATOR_INFO {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierungsschlüssel zurücksetzen.
        /// </summary>
        public static string RESET_AUTHENTICATOR_KEY {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Authentifikator-App-Schlüssel wurde zurückgesetzt. Sie müssen Ihre Authentifikator-App mit dem neuen Schlüssel konfigurieren..
        /// </summary>
        public static string RESET_AUTHENTICATOR_STATUS {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Prozess deaktiviert 2FA, bis Sie Ihre Authentifikator-App überprüft haben. Wenn Sie Ihre Authentifikator-App-Konfiguration nicht abschließen, verlieren Sie möglicherweise den Zugriff auf Ihr Konto..
        /// </summary>
        public static string RESET_AUTHENTICATOR_TEXT {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        public static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um sich einzuloggen.
        /// </summary>
        public static string RESET_PASSWORD_CLICK_HERE_TO_LOGIN {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CLICK_HERE_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigung fürs Passwort zurücksetzen.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie hier, um sich einzuloggen.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_CLICK_HERE {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_CLICK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde zurückgesetzt. Bitte.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_TEXT1 {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte setzen Sie Ihr Passwort zurück, indem Sie hier &lt;a href=&apos;{0}&apos;&gt;klicken&lt;/a&gt;..
        /// </summary>
        public static string RESET_PASSWORD_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde zurückgesetzt..
        /// </summary>
        public static string RESET_PASSWORD_YOUR_PASSWORD_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_YOUR_PASSWORD_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellungscodes zurücksetzen.
        /// </summary>
        public static string RESET_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("RESET_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzen Sie Ihr Passwort zurück.
        /// </summary>
        public static string RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Rolle {0} ist nicht vorhanden..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifizierungscode senden.
        /// </summary>
        public static string SEND_VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie den Zwei-Faktor-Authentifizierungsanbieter aus:.
        /// </summary>
        public static string SEND_VERIFICATION_CODE_SELECT {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_CODE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifizierung-E-Mail senden.
        /// </summary>
        public static string SEND_VERIFICATION_EMAIL {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort festlegen.
        /// </summary>
        public static string SET_PASSWORD {
            get {
                return ResourceManager.GetString("SET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde festgelegt.
        /// </summary>
        public static string SET_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("SET_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen lokalen Benutzernamen / Passwort für diese Seite. Fügen Sie ein lokales Konto hinzu, damit Sie sich ohne externe Anmeldung anmelden können..
        /// </summary>
        public static string SET_PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("SET_PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort festlegen.
        /// </summary>
        public static string SET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("SET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die externe Anmeldung wurde hinzugefügt.
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_ADDED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die externe Anmeldung wurde entfernt.
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_REMOVED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben neue Wiederherstellungscodes generiert.
        /// </summary>
        public static string STATUS_GENERATE_CODES {
            get {
                return ResourceManager.GetString("STATUS_GENERATE_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Profil wurde aktualisiert.
        /// </summary>
        public static string STATUS_MESSAGE_PROFILE_HAS_BEEN_RESET {
            get {
                return ResourceManager.GetString("STATUS_MESSAGE_PROFILE_HAS_BEEN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Profil wurde aktualisiert.
        /// </summary>
        public static string STATUS_PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("STATUS_PROFILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifizierungs-E-Mail gesendet Bitte überprüfen Sie Ihre E-Mails..
        /// </summary>
        public static string STATUS_UPDATE_PROFILE_EMAIL_SEND {
            get {
                return ResourceManager.GetString("STATUS_UPDATE_PROFILE_EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IProtectedUserStore&lt;TUser&gt; which is required when ProtectPersonalData = true..
        /// </summary>
        public static string StoreNotIProtectedUserStore {
            get {
                return ResourceManager.GetString("StoreNotIProtectedUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQueryableRoleStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIQueryableRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQueryableUserStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIQueryableUserStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRoleClaimStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIRoleClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIRoleClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserAuthenticationTokenStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserAuthenticationTokenStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticationTokenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserAuthenticatorKeyStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserAuthenticatorKeyStore {
            get {
                return ResourceManager.GetString("StoreNotIUserAuthenticatorKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserClaimStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserClaimStore {
            get {
                return ResourceManager.GetString("StoreNotIUserClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserConfirmationStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserConfirmationStore {
            get {
                return ResourceManager.GetString("StoreNotIUserConfirmationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserEmailStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserEmailStore {
            get {
                return ResourceManager.GetString("StoreNotIUserEmailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserLockoutStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserLockoutStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLockoutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IUserLoginStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserLoginStore {
            get {
                return ResourceManager.GetString("StoreNotIUserLoginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IUserPhoneNumberStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserPasswordStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPasswordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IProtectedUserStore &lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserPhoneNumberStore {
            get {
                return ResourceManager.GetString("StoreNotIUserPhoneNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IUserRoleStore&lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserRoleStore {
            get {
                return ResourceManager.GetString("StoreNotIUserRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserTwoFactorRecoveryCodeStore&lt;User&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserSecurityStampStore {
            get {
                return ResourceManager.GetString("StoreNotIUserSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IProtectedUserStore &lt;TUser&gt; ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserTwoFactorRecoveryCodeStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorRecoveryCodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUserTwoFactorStore&lt;TUser&gt;ist nicht implementiert..
        /// </summary>
        public static string StoreNotIUserTwoFactorStore {
            get {
                return ResourceManager.GetString("StoreNotIUserTwoFactorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das {0} muss mindestens {2} und darf höchstens {1} Zeichen lang sein..
        /// </summary>
        public static string The__0__must_be_at_least__2__and_at_max__1__characters_long_ {
            get {
                return ResourceManager.GetString("The {0} must be at least {2} and at max {1} characters long.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei-Faktor-Authentifizierungs-Code ist erforderlich.
        /// </summary>
        public static string TWOFACTORCODE_REQUIRED {
            get {
                return ResourceManager.GetString("TWOFACTORCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht erfolgreiche Anmeldung mit Authentifizierungsanbieter..
        /// </summary>
        public static string UNSUCCESSFUL_LOGIN_WITH_SERVICE {
            get {
                return ResourceManager.GetString("UNSUCCESSFUL_LOGIN_WITH_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort aktualisieren.
        /// </summary>
        public static string UPDATE_PASSWORD {
            get {
                return ResourceManager.GetString("UPDATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer mit ID  &apos;{0}&apos; konnte nicht geladen werden..
        /// </summary>
        public static string USER_NOTFOUND {
            get {
                return ResourceManager.GetString("USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerprofil.
        /// </summary>
        public static string User_profile {
            get {
                return ResourceManager.GetString("User profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer hat bereits ein Passwort festgelegt..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer ist bereits in der Rolle &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer ist gesperrt..
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Sperrung ist für diesen Benutzer nicht aktiviert..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer {0} ist nicht vorhanden..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer hat die Rolle &apos;{0}&apos; nicht..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifizierungscode.
        /// </summary>
        public static string VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungscode wird benötigt.
        /// </summary>
        public static string VERIFICATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen.
        /// </summary>
        public static string VERIFY {
            get {
                return ResourceManager.GetString("VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie sich von IdentityServer abmelden?.
        /// </summary>
        public static string WOULD_YOU_LIKE_TO_LOGOUT {
            get {
                return ResourceManager.GetString("WOULD_YOU_LIKE_TO_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen mindestens eine Erlaubnis auswählen.
        /// </summary>
        public static string You_must_pick_at_least_one_permission {
            get {
                return ResourceManager.GetString("You must pick at least one permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Emailadresse.
        /// </summary>
        public static string Your_email_address {
            get {
                return ResourceManager.GetString("Your email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Benutzerkennung.
        /// </summary>
        public static string Your_user_identifier {
            get {
                return ResourceManager.GetString("Your user identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Benutzerprofilinformationen (Vorname, Nachname usw.).
        /// </summary>
        public static string Your_user_profile_information__first_name__last_name__etc__ {
            get {
                return ResourceManager.GetString("Your user profile information (first name, last name, etc.)", resourceCulture);
            }
        }
    }
}
